### ISSUE TITLE
Support comments in .env file

### ISSUE THREAD

**Issue by evandam** [kHRISl33t/runtime-env-cra#15]
Hey @kHRISl33t thanks for the project! I was wondering if it would be possible to support comments in the .env file though? Hoping it's easy enough to filter out lines that start with `#` so it would allow us to document our environment variables in the code.

Thanks!

**Comment by seanblonien** [comment]
Simple comments should be supported I believe, take a look at https://github.com/kHRISl33t/runtime-env-cra/pull/6

**Comment by kHRISl33t** [comment]
Yes. You can do that if you start your line with `#`
